displayName=Kick History
author=Skill Cape
description=Logs names of players kicked from Friends Chat to side panel and optional discord webhook
tags=friends,chat,kick,log,logger,history
plugins=com.KickHistory.KickHistory
build=standard